# Site settings
title: Samuel James Bell
email: samueljamesbell@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Samuel James Bell is a Software Engineer.
tagline: "Engineer, writer, technophobe."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://samueljamesbell.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
